use supply_chain;
show tables;
-- basics query....1
-- Read the data from all the tables.......
SELECT * FROM supplier;
SELECT * FROM product;
SELECT * FROM orderitem;
SELECT * FROM orders;
SELECT * FROM customer;
-- basics query....2
-- Find the country-wise count of customers.....
select * from customer;
select Country,count(Id) as total_num_of_customers_in_each_country from customer group by Country order by  total_num_of_customers_in_each_country desc;
/*SELECT country, COUNT(id) AS count_cust 
FROM customer 
GROUP BY country 
ORDER BY count_cust DESC; */
-- basic query...3
-- Display the products that are not discontinued.....
select * from product;
select ProductName from product where IsDiscontinued = 1;
/*SELECT * FROM product 
WHERE isdiscontinued = '1';*/
-- basic query ...4
-- Display the list of companies along with the product name that they are supplying.....
select * from supplier;
select s.CompanyName,p.ProductName from supplier s inner join product p on s.Id=p.SupplierId;
/*SELECT s.companyname, p.productname 
FROM supplier s 
JOIN product p ON s.id = p.supplierid;*/
-- basic query ...5
-- Display customer information about who stays in 'Mexico'.....
show tables;
select * from customer;
-- select * from customer where Country = 'Mexico';
SELECT * FROM customer 
WHERE country = 'Mexico';
-- basic query ...6 
-- Display the costliest item that is ordered by the customer.....
select * from  orderitem;
SELECT c.id AS customer_id, p.productname, p.unitprice 
FROM customer c 
JOIN orders o ON c.id = o.customerid
JOIN orderitem oi ON o.id = oi.orderid
JOIN product p ON p.id = oi.productid
WHERE (c.id, p.unitprice) IN (
    SELECT c.id, MAX(p.unitprice) 
    FROM product p
    JOIN orderitem oi ON oi.productid = p.id
    JOIN orders o ON o.id = oi.orderid
    JOIN customer c ON o.customerid = c.id
    GROUP BY c.id
);
-- basic query ....7
-- Display supplier ID who owns the highest number of products.....
WITH max_p AS (
    SELECT s.id, COUNT(p.id) AS cnt_prod
    FROM supplier s 
    JOIN product p ON p.supplierid = s.id
    GROUP BY s.id
)
SELECT * FROM max_p 
WHERE cnt_prod IN (SELECT MAX(cnt_prod) FROM max_p);
-- basic query....8
-- Display month-wise and year-wise counts of the orders placed......
SELECT YEAR(orderdate) AS year, MONTH(orderdate) AS month, COUNT(id) AS order_count 
FROM orders
GROUP BY YEAR(orderdate), MONTH(orderdate) 
ORDER BY year ASC, month ASC;
-- basic query...9
--  Which country has the maximum number of suppliers?.....
WITH max_c AS (
    SELECT country, COUNT(id) OVER(PARTITION BY country) AS count
    FROM supplier
)
SELECT DISTINCT * FROM max_c 
WHERE count IN (SELECT MAX(count) FROM max_c);
-- basic query...10
-- Which customers did not place any orders?...
SELECT * FROM customer
WHERE id NOT IN (SELECT customerid FROM orders);
-- intdermediate queries....
-- query...1
-- Arrange the Product ID and Name based on the high demand by the customer....
SELECT p.id AS product_id, p.productname, SUM(oi.quantity) AS total_quantity
FROM orderitem oi 
JOIN product p ON p.id = oi.productid
GROUP BY p.id, p.productname 
ORDER BY total_quantity DESC;
-- query....2
-- Display the total number of orders delivered every year....
SELECT YEAR(orderdate) AS year, COUNT(id) AS total_orders 
FROM orders 
GROUP BY YEAR(orderdate);
-- query....3
-- Calculate year-wise total revenue......
SELECT YEAR(orderdate) AS year, SUM(totalamount) AS total_revenue 
FROM orders 
GROUP BY YEAR(orderdate);
-- query....4
-- Display the customer details whose order amount is maximum including his past orders....
SELECT c.*, SUM(totalamount) AS total_order_amount 
FROM customer c
JOIN orders o ON o.customerid = c.id
GROUP BY c.id 
ORDER BY SUM(totalamount) DESC 
LIMIT 1;
-- query....5
-- Display the total amount ordered by each customer from high to low.....
SELECT c.*, SUM(totalamount) AS total_order_amount 
FROM customer c
JOIN orders o ON o.customerid = c.id
GROUP BY c.id 
ORDER BY SUM(totalamount) DESC;
-- query......6
-- List the current and previous order dates for each customer......
SELECT c.id AS customerid, c.firstname, o.orderdate
FROM customer c 
JOIN orders o ON o.customerid = c.id
ORDER BY customerid, orderdate;
-- query....7
-- Find out the top 3 suppliers in terms of revenue generated by their products......
SELECT s.id AS supplierid, s.contactname, SUM(quantity * oi.unitprice) AS totalrevenue
FROM supplier s
JOIN product p ON s.id = p.supplierid
JOIN orderitem oi ON oi.productid = p.id
JOIN orders o ON o.id = oi.orderid
GROUP BY s.id, s.contactname 
ORDER BY totalrevenue DESC 
LIMIT 3;
-- query....8
-- Display the latest order date of all the customers with customer details.....
SELECT c.*, MAX(orderdate) AS latest_order_date
FROM customer c
JOIN orders o ON o.CustomerId = c.id
GROUP BY c.id;
-- query.....9
-- Display the product name and supplier name for each order.......
SELECT oi.orderid, p.productname, s.contactname AS suppliername
FROM supplier s 
JOIN product p ON p.supplierid = s.id
JOIN orderitem oi ON oi.productid = p.id
JOIN orders o ON o.id = oi.orderid;
-- advanced queries......
-- query......1
-- Fetch the customer details who ordered more than 10 products in a single order.....
WITH product_ordered AS (
    SELECT DISTINCT c.*, COUNT(o.id) OVER(PARTITION BY c.id) AS count
    FROM customer c 
    JOIN orders o ON o.customerid = c.id
)
SELECT * FROM product_ordered 
WHERE count > 10 
ORDER BY count DESC;
-- query .......2
-- Display all the product details with the ordered quantity size as 1......
SELECT p.* 
FROM product p 
JOIN orderitem oi ON oi.productid = p.id 
WHERE quantity = 1;
-- query.......3
-- Display the companies that supply products whose cost is above 100......
SELECT DISTINCT s.* 
FROM supplier s 
JOIN product p ON p.SupplierId = s.id
JOIN orderitem oi ON oi.productid = p.id 
WHERE oi.unitprice > 100;
-- query........4
-- Display the customer list who belongs to the same city and country arranged country-wise.....
SELECT DISTINCT c1.id, c1.firstname, c2.FirstName, c1.city, c1.country
FROM customer c1 
JOIN customer c2 ON (c1.city, c1.country) = (c2.city, c2.country)
WHERE c1.id <> c2.id
ORDER BY c1.country;
-- expert...level.....queries..
-- query......1
-- Calculate the total amount saved in each order and rank by savings.......
SELECT oi.orderid, SUM((p.unitprice - oi.unitprice) * oi.quantity) AS total_amount_saved
FROM product p 
JOIN orderitem oi ON p.id = oi.productid
GROUP BY oi.orderid 
ORDER BY total_amount_saved DESC;
-- query.....2
--  Market Research for Mr. Kavin.......
-- a. High-demand products
SELECT p.productname, SUM(oi.quantity) AS total_demand
FROM product p
JOIN orderitem oi ON p.id = oi.productid
GROUP BY p.productname
ORDER BY total_demand DESC;

-- b. Competitors for high-demand products
SELECT DISTINCT s.contactname, p.productname
FROM orderitem oi 
JOIN product p ON p.id = oi.productid
JOIN supplier s ON p.supplierid = s.id;